import { ReactNode } from 'react';

import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';

import Footer from '@/components/Footer';
import Header from '@/components/Header';

import './globals.css';

const poppins = Poppins({
  weight: ['400', '600'],
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: 'Bazario',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className}>
      <body
        className={`flex h-full w-screen flex-col items-center bg-secondary ${poppins.variable}`}
      >
        <Header />
        <main> {children}</main>
        <Footer />
      </body>
    </html>
  );
}
